### ISSUE TITLE
Lil Gnosis - should be EIP 712 (not 721)

### ISSUE THREAD

**Issue by rahul-kothari** [m1guelpf/lil-web3#9]
https://github.com/m1guelpf/lil-web3/blob/main/src/LilGnosis.sol
Love the work you have done here!

A small nit-pick/point of confusion:
https://github.com/m1guelpf/lil-web3/blob/main/src/LilGnosis.sol#L47 - this should be eip712 and not 721 right? AFAIK, 721 is the NFT standard?
I think this is there throughout the contract.

Anyway great great stuff my man!

**Comment by m1guelpf** [comment]
whoopsie, always get those messed up. do you want to submit a PR to fix this (and get that github clout lol) or should I fix?
